{% set name = "emptylog" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emptylog-{{ version }}.tar.gz
  sha256: 2e362f61a94829f0a9ec32539094e36e5d6dca23562d2f18993278cae35fd151

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}
    - printo >=0.0.5

test:
  imports:
    - emptylog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/emptylog
  summary: Mimicking the logger protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
