{% set name = "emptylog" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emptylog-{{ version }}.tar.gz
  sha256: fc60879c2e954e22e87dd3bdfef0ca833871873f2584d9fc03332a7cee32ada9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7
    - typing-extensions
    - printo >=0.0.2

test:
  imports:
    - emptylog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/emptylog
  summary: Mimicking the logger protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
